services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - multibank-network

  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=auth_db sslmode=disable
      - JWT_SECRET=simple-secret-12345
    networks:
      - multibank-network

  accounts-service:    
    build: ./accounts-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=auth_db sslmode=disable
      - JWT_SECRET=simple-secret-12345
    networks:
      - multibank-network
 
  transfer-service:
    build: ./transfer-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=auth_db sslmode=disable
      - JWT_SECRET=simple-secret-12345
    depends_on:
      - auth-service
      - accounts-service
    networks:
      - multibank-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" 
    # УБИРАЕМ network_mode: "host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080  # Меняем позже для продакшена
    depends_on:
      - auth-service
      - accounts-service
      - transfer-service
    networks:
      - multibank-network

volumes:
  postgres_data:

networks:
  multibank-network:
    driver: bridge